import * as bodyParser from 'body-parser';
import * as cors from 'cors';
import * as express from 'express';
import * as helmet from 'helmet';
import * as morgan from 'morgan';
import 'reflect-metadata';
import * as swaggerJSDoc from 'swagger-jsdoc';
import * as swaggerStats from 'swagger-stats';
import * as swaggerUi from 'swagger-ui-express';
import {createConnection} from 'typeorm';
import routes from './routes';

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['**/routes/auth.ts', '**/controller/Admin/*.ts'],
};

const specs = swaggerJSDoc(options);

const SENSITIVE_KEYS = ['password', 'token', 'auth', 'authorization', 'jwt'];

const sanitizeLogBody = (value: any): any => {
  if (Array.isArray(value)) {
    return value.map(item => sanitizeLogBody(item));
  }

  if (value && typeof value === 'object') {
    return Object.keys(value).reduce((acc: {[key: string]: any}, key) => {
      const normalizedKey = key.toLowerCase();
      if (SENSITIVE_KEYS.includes(normalizedKey)) {
        acc[key] = '[REDACTED]';
      } else {
        acc[key] = sanitizeLogBody(value[key]);
      }
      return acc;
    }, {});
  }

  return value;
};

const startServer = () => {
  const app = express();
  app.use(cors());
  app.use(swaggerStats.getMiddleware({}));
  app.use(helmet());
  app.use(bodyParser.json());
  morgan.token('safe-body', req => {
    const sanitized = sanitizeLogBody(req.body || {});
    return JSON.stringify(sanitized);
  });
  app.use(
    morgan(
      '[:date[iso]] :remote-addr :method :url status=:status bytes=:res[content-length] time=:response-time ms body=:safe-body',
    ),
  );
  // Set all routes from routes folder
  app.use('/', routes);
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
  app.listen(3000, async () => {
    console.log('Server started on port 3000!');
  });
};

const connectWithRetry = (retries: number = 20, delayMs: number = 3000) => {
  createConnection()
    .then(() => {
      startServer();
    })
    .catch(e => {
      console.log('Database connection failed, retrying...', e);
      if (retries <= 1) {
        console.log('Database connection failed after retries, exiting.');
        process.exit(1);
        return;
      }
      setTimeout(() => connectWithRetry(retries - 1, delayMs), delayMs);
    });
};

// Connects to the Database -> then starts express
connectWithRetry();
